# ----------- CONFIGURABLE START -----------
title:            "Lily Holloway"
description:      "poetry and writing by Lily Holloway"
url:              https://lilyholloway.co.nz # Site url, without a slash at the end.
signoff:          "Lily" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         Poems
    url:          /
    external:     false
  - name:         About
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"
      
      
      
theme: tufte-pandoc-jekyll
gems:
  - jekyll-pandoc
